repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.3
    hooks:
      - id: pylint
        args: ["--rcfile=pyproject.toml"]
        additional_dependencies: [jax, jaxlib, astropy, numpy, matplotlib]
